# fly.toml app configuration file generated for sherwood-energy-mon on 2024-03-07T12:39:53-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sherwood-energy-mon'
primary_region = 'sjc'

[build]
  [build.args]
      GO_VERSION = '1.21.5'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory_mb = 512
  cpu_kind = 'shared'
  cpus = 1
